#ifndef ACTION_TYPE_H
#define ACTION_TYPE_H

#include <cstdint>

enum ActionType : const uint8_t {
    MOVE_RIGHT_KEY_DOWN = 0x01,
    MOVE_RIGHT_KEY_UP,
    MOVE_LEFT_KEY_DOWN,
    MOVE_LEFT_KEY_UP,
    JUMP_KEY_DOWN,
    JUMP_KEY_UP,
    SHOOT_KEY_DOWN,
    SHOOT_KEY_UP,
    LOOKING_RIGHT_KEY_DOWN,
    LOOKING_RIGHT_KEY_UP,
    LOOKING_LEFT_KEY_DOWN,
    LOOKING_LEFT_KEY_UP,
    LOOKING_UP_KEY_DOWN,
    LOOKING_UP_KEY_UP,
    LOOKING_DOWN_KEY_DOWN,
    LOOKING_DOWN_KEY_UP
};

#endif  // ACTION_TYPE_H
