name: Run pre-commit checks

on: [push, pull_request]

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install cppcheck 2.13.0
        run: |
          sudo apt-get update
          sudo apt-get install -y wget build-essential cmake
          wget https://github.com/danmar/cppcheck/archive/refs/tags/2.13.0.tar.gz -O cppcheck-2.13.0.tar.gz
          tar -xzf cppcheck-2.13.0.tar.gz
          cd cppcheck-2.13.0
          mkdir build && cd build
          cmake ..
          make -j$(nproc)
          sudo make install
          cppcheck --version

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit

      - name: Run pre-commit hooks
        run: |
          pre-commit run --all-files
